### ISSUE TITLE
problem with different image file types, train.txt

### ISSUE THREAD

**Issue by VanitarNordic** [AlexeyAB/Yolo_mark#1]
Hello,

I have two issues with this software.

1) it seems it does not generate the `train.txt` file intself and we gonna make it before start labeling, isn't it?

2) I have some images with PNG format, the software seems to be unable to read them.

**Comment by AlexeyAB** [comment]
@VanitarNordic 

1. No. Yolo_mark generates `train.txt` automatically. You should create only `synset.txt`, or you may to not create it.

2. Yes, but you can rename all `.png`, `.jpeg`, `.bmp` files to `.jpg`-files, and it will work.

**Comment by VanitarNordic** [comment]
Yess, Now it woks quite perfectly. it is good software. congratulations!

**Comment by AlexeyAB** [comment]
I fixed it.
Now there are supported files: jpg, jpeg, bmp, png, ppm - and UPPER CASE extensions.
