### ISSUE TITLE
Images are stretching

### ISSUE THREAD

**Issue by tekeburak** [AlexeyAB/Yolo_mark#111]
_First of all, thank you @AlexeyAB for such a work._

While I was trying to label my images, the images were stretched.
And it's affect the coordinates.
Same problem has been stated before at #3. It is said that it was not alter the coordinates but it was.
Because I have checked the pre-created ground truth labels on Yolo_mark, bounding box locations were wrong.

> My image size: w:720 h:576
OpenCV version: 3.4.3
Ubuntu 16.04 LTS

**Comment by linuxTown** [comment]
Hi,
you can try my fork of this repository, I added images border padding, so now images shouldn't stretch. Let me know if you need any other functionality.
https://github.com/linuxTown/Yolo_mark

**Comment by tekeburak** [comment]
Hi,
Thank you for your reply.
Now, I am using [labelImg](https://github.com/tzutalin/labelImg) repo for labeling and checking my dataset.

**Comment by AlexeyAB** [comment]
@tekeburak Hi,

> While I was trying to label my images, the images were stretched.
> And it's affect the coordinates.
> Same problem has been stated before at #3. **It is said that it was not alter the coordinates but it was.**
> Because I have checked the pre-created ground truth labels on Yolo_mark, bounding box locations were wrong.

What do you mean?
Yolo uses relative coordinates, so it doesn't depends on images size. So if you resize image from 500x500 to the 200x800, labels (values in the txt-file) will be absolutely the same.

**Comment by tekeburak** [comment]
> What do you mean?
> Yolo uses relative coordinates, so it doesn't depends on images size. So if you resize image from 500x500 to the 200x800, labels (values in the txt-file) will be absolutely the same.

I know that Yolo uses relative coordinates. What I'd like to say, while using Yolo_mark, Image are stretching that I mentioned before. After labeling the stretching image, I have checked the label using another tool and bounding boxes were shifted.

**Comment by AlexeyAB** [comment]
@tekeburak 

> After labeling the stretching image, **I have checked the label using another tool and bounding boxes were shifted.**

Can you show screenshot?

**Comment by saratrajput** [comment]
@AlexeyAB I have the same problem. Here is a screenshot.
![yolo_mark_issue](https://user-images.githubusercontent.com/29677848/76492066-9cec4280-6472-11ea-90c9-8b2c1f6f922c.png)

**Comment by AlexeyAB** [comment]
@saratrajput This is normal, it doesn't affect on coordinates, because coordinates are normalized.

**Comment by saratrajput** [comment]
@AlexeyAB Thanks for the reply. It's fine for now.
