### ISSUE TITLE
error in running linux_mark.sh

### ISSUE THREAD

**Issue by VellalaVineethKumar** [AlexeyAB/Yolo_mark#112]
[ 50%] Building CXX object CMakeFiles/yolo_mark.dir/main.cpp.o
[100%] Linking CXX executable yolo_mark
[100%] Built target yolo_mark

cse@cse-w1:~/vineeth/Yolo_mark-master$ ./linux_mark.sh
Example how to start marking bouded boxes for training set Yolo v2
File opened for output: x64/Release/data/train.txt
File loaded: x64/Release/data/obj.names
exception: OpenCV(3.4.2) /tmp/build/80754af9/opencv-suite_1535558553474/work/modules/highgui/src/window.cpp:615: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvNamedWindow'

so i installed 
cse@cse-w1:~/vineeth/Yolo_mark-master$ sudo apt-get install libgtk2.0-dev 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libgtk2.0-dev is already the newest version (2.24.30-1ubuntu1.16.04.2).
0 upgraded, 0 newly installed, 0 to remove and 306 not upgraded.

cse@cse-w1:~/vineeth/Yolo_mark-master$ sudo apt-get install pkg-config
Reading package lists... Done
Building dependency tree       
Reading state information... Done
pkg-config is already the newest version (0.29.1-0ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 306 not upgraded.

and tried to run ./linux_mark.sh again but i still get the same error! 

please help!

**Comment by VellalaVineethKumar** [comment]
i am using Anaconda packages (opencv) i did not cmake opencv files

**Comment by AlexeyAB** [comment]
@VellalaVineethKumar Try to Reinstall Anaconda packages (opencv).

**Comment by VellalaVineethKumar** [comment]
okay thank you!

**Comment by aerdengiz** [comment]
Well, I have the same issue but I wasn't able to solve it following the instructions here:
I'm on Ubuntu 18.04.LTS
I use Anaconda, so I did un-install and re-install opencv 3.4.2
But, I still get the same message:
![image](https://user-images.githubusercontent.com/48405279/54083954-e7505600-432a-11e9-92be-949cb1d85551.png)

**Comment by VellalaVineethKumar** [comment]
@aerdengiz 
* downgrade your pip
* install OpenCV by pip install opencv-python==3.2.1
* make clean
* make
(make sure you have set opencv=1 in your Makefile

**Comment by aerdengiz** [comment]
Thank you!

Ali Erdengiz

ali.erdengiz@gmail.com

C[FR] +33 (0) 7 67 70 96 92
C[US] +1 (415) 939 3476

**Comment by DarylWM** [comment]
Hi @AlexeyAB . I'm blocked with the same issue on Ubuntu 18.04 and Anaconda Python 3.6. I successfully did the steps you suggested above...

> you should recompile OpenCV
> And then recompile Yolo_mark:

... but I still get the same error when I try to run linux_mark.sh.

![image](https://user-images.githubusercontent.com/1016303/55542453-cfde7000-5712-11e9-8ad8-21ab5fddfb39.png)

Not sure what I'm doing wrong.

**Comment by the-cat-crying** [comment]
I also appear the same problem

**Comment by s85153546** [comment]
> This is the OpenCV error, not Yolo_mark.
> 
> So after
> 
> ```
> sudo apt-get install libgtk2.0-dev
> sudo apt-get install pkg-config
> ```
> 
> you should recompile OpenCV
> 
> ```
> cmake -D CMAKE_BUILD_TYPE=RELEASE -D BUILD_EXAMPLES=OFF -D WITH_FFMPEG=ON -D WITH_V4L=OFF -D WITH_LIBV4L=ON
> make all -j8
> make install
> ```
>  
> And then recompile Yolo_mark:
> 
> ```
> cmake .
> make
> ./linux_mark.sh
> ```

sorry I still cannot find my opencv
I occurence this
![截圖 2020-05-21 上午12 23 24](https://user-images.githubusercontent.com/55569372/82471458-4e55c700-9af9-11ea-8192-0629c61f486e.png)
