### ISSUE TITLE
Correct way of calculating the relative coordinates

### ISSUE THREAD

**Issue by VanitarNordic** [AlexeyAB/Yolo_mark#13]
Hello,

I have a discussion about anchors and relative coordinates of YOLO here. it seems we had a mistake so far, maybe.

it is here: https://github.com/Jumabek/darknet_scripts/issues/8#issuecomment-322697885

if you are agree with him then Please update the repo with this consideration then I will make a test with new relative coordinates and new anchors.

**Comment by AlexeyAB** [comment]
Hi,
* This is not relative to Yolo_mark. This link relative to calculating anchors.
* christopher5106 answered you how to get square anchor relative to square network size (416x416), but not about how to get the correct good anchors for your dataset: https://github.com/Jumabek/darknet_scripts/issues/8#issuecomment-322702980

> Here I'm just telling you how to check to get square anchors:

* Only original Linux repo had errors when using non-square networks some time ago, whether Joseph corrected these errors - I do not know. My repo can successfully use non-square networks: https://github.com/AlexeyAB/darknet

**Comment by VanitarNordic** [comment]
He actually says that we must calculated the relative coordinates differently, not by dividing the absolute one over image's height and width. That's why I thought the way of calculating the relative coordinates could be wrong, that's the reason the anchors are not correct, because they don't work in practice actually.
is that the case or I'm mistaken?

**Comment by AlexeyAB** [comment]
You are mistaken.
He telling you **how to get square anchors which won't work** in the yolo training: https://github.com/Jumabek/darknet_scripts/issues/8#issuecomment-322702980

> Here **I'm just telling you how to check to get square anchors**: this is because your boxes which looks square are not if you consider them relatively to the image (that you resize in a square) . But **these anchors won't work in the yolo training**.

**Comment by VanitarNordic** [comment]
Okay, Thank you very much.

Actually the repo author himself had no idea about it but anyway I used those generated anchors and they did not work. they reduced the accuracy.
