### ISSUE TITLE
Overlapped objects

### ISSUE THREAD

**Issue by ToshiEAB** [AlexeyAB/Yolo_mark#171]
Dear AlexeyAB

I am using your program (https://github.com/AlexeyAB/Yolo_mark) to train a YOLO model. Specifically, after the training, I want to detect several small fish at once on a video even when they somewhat overlap (e.g., two fish making an "X" shape") with each other. What is a good way of training to achieve that goal? Should I use images showing two (or more) fish overlapping each other and put a label on each of the fish? Or should I use images showing only a single fish and put a label? If it is difficult to detect two separate fish at once when they are making an "X" shape, should I consider the X shape as a "negative" sample and then use a tracker (e.g., Kalman filter) to make a prediction of the motion of each fish.

Any advice would be helpful.

Thanks in advance,
ToshiEAB

**Comment by AlexeyAB** [comment]
@ToshiEAB Hi,

Several overlapped objects with the same class_id is the most difficult case in object detection.
Currently there are 3 features in road-map for implementing: 
* Repulsion Loss (CVPR 2018) https://github.com/AlexeyAB/darknet/issues/3113
* Soft-IoU layer (CVPR 2019) https://github.com/AlexeyAB/darknet/issues/4701
* Yolact instance segmentation, each instance of object in its own channel: https://github.com/AlexeyAB/darknet/issues/3048

> should I consider the X shape as a "negative" sample and then use a tracker (e.g., Kalman filter) to make a prediction of the motion of each fish.

Yes, you can try to do this. 
There is no best practice for this case.

**Comment by ToshiEAB** [comment]
@AlexeyAB 

Thanks you very much for the information. I'm glad to know that there are several possibilities to tackle this problem. I will try those you suggested and will ask you if I get stuck.

Best regards,
ToshiEAB
