### ISSUE TITLE
Program crashes on pressing ESC

### ISSUE THREAD

**Issue by VanitarNordic** [AlexeyAB/Yolo_mark#2]
Hello,

When the number of images is relatively big (it does not happen when the number of images is around 10 .. 50 or something but it happens with it is around 250 images), pressing the ESC key will cause the program to crash. Please check the issue. Finally it seems that it **does** the job but with a crash. Platform: W10-64

![2017-02-05_11-42-57](https://cloud.githubusercontent.com/assets/18719591/22624672/562d4bf6-eb98-11e6-8e34-2426bf1ae958.png)

**Comment by AlexeyAB** [comment]
I can't reproduce this crash even with more than 10 000 images on Win7 x64 & MSVS2015.

Also I added support background-images without objects, that you want: https://github.com/AlexeyAB/Yolo_mark/commit/37baffc60926bab7f27c6eae1eea1a2d716b1c56

To add background-images without objects - simply you should press space-button for each that image.

Check mark indicates that the image is added:
![background_image](https://cloud.githubusercontent.com/assets/4096485/23615953/33db3f00-0299-11e7-9d5a-0f8dc5d356dd.jpg)

**Comment by VanitarNordic** [comment]
Have you tested inside VS2015 or you did the test by running the software from command line?

**Comment by AlexeyAB** [comment]
I ran Yolo from command line.

**Comment by VanitarNordic** [comment]
interesting. I will upload a video for you to consider the issue.

**Comment by VanitarNordic** [comment]
I recorded a video. Please consider when I press the ESC, it stops working. Although I use Windows10-x64, but I don't think it matters. 

https://dl.dropboxusercontent.com/u/40078654/2017-03-06_21-18-50.mp4

**Comment by AlexeyAB** [comment]
Try to add this code at the end of `main()`-function:

```
	catch (...) {
		std::cout << "unknown exception \n";
	}

    std::cout << "step-1 \n";
    cv::destroyAllWindows()'
    std::cout << "step-2 \n";

    return 0;
}
```
What will be the output of the program before crash?

**Comment by VanitarNordic** [comment]
The program does the job, it creates annotations and txt files but it creates this crash also. I'll add the code

**Comment by VanitarNordic** [comment]
Okay, I tried the code, but it does not fix the problem. also it does not print anything more in the console after crash.

**Comment by VanitarNordic** [comment]
Besides, look at this picture. The name of the last image in the dataset is `0153.jpg` , why it is repeated? also **trackbar_value** has repeated.

![2017-03-07_1-17-08](https://cloud.githubusercontent.com/assets/18719591/23631608/4204412c-02d4-11e7-9bd1-81231043c69e.jpg)

**Comment by AlexeyAB** [comment]
Now I added catch Windows-SEH exceptions.

Later if I'll create Windows 10 virtual machine, then I'll try to solve this. But I think it does not interfere with work now.

**Comment by VanitarNordic** [comment]
I solved the case by replacing the break with exit(0) in the code:

`if (pressed_key == 27)  exit(0);  // ESC - exit`

Now it works flawlessly.
