### ISSUE TITLE
CMake can not determine linker language for target: yolo_mark

### ISSUE THREAD

**Issue by OhMeuMenino** [AlexeyAB/Yolo_mark#4]
When I do cmake . I get the folowwing error:

`- The C compiler identification is GNU 6.3.1
-- The CXX compiler identification is GNU 6.3.1
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done

CMake Error: CMake can not determine linker language for target: yolo_mark

CMake Error: Cannot determine link language for target "yolo_mark".

-- Generating done
`

**Comment by AlexeyAB** [comment]
Try replacing the contents of `CMakeLists.txt`-file to this lines. Does it work well?

```
cmake_minimum_required(VERSION 2.8)
project( yolo_mark CXX )
find_package( OpenCV REQUIRED )

# file(GLOB_RECURSE sources *.cpp *.h)
set( sources main.cpp )

add_executable( yolo_mark ${sources} )

target_compile_options( yolo_mark PUBLIC -std=c++11 -fpermissive -w -Wall )

target_link_libraries( yolo_mark ${OpenCV_LIBS} -L/usr/lib64 -ldl )

```

**Comment by OhMeuMenino** [comment]
Yes it works 👍 
Thank you!

**Comment by AlexeyAB** [comment]
I added this fix in last commit: https://github.com/AlexeyAB/Yolo_mark/commit/7efc1a26ca0656c8aaf7d17c83f467910624383a
