### ISSUE TITLE
number of classes

### ISSUE THREAD

**Issue by maharleeeka** [AlexeyAB/Yolo_mark#50]
is it possible to use Yolo Mark in annotating for more than 10 classes?

**Comment by AlexeyAB** [comment]
Yes, you can use any number of classes.
1. Just add names of classes to the `obj.names` (or empty lines)
2. Run: `./yolo_mark data/img data/train.txt data/obj.names`
3. And move scroll of classes at the top of window:
![image](https://user-images.githubusercontent.com/4096485/40585144-1784ae86-61b6-11e8-81dc-fc7dbb239a32.png)

**Comment by maharleeeka** [comment]
@AlexeyAB Okay, thank youuu. I forgot about the slider, I thought the only way to change class is to  press 0-9.
