### ISSUE TITLE
command window and the rendered characters on the image

### ISSUE THREAD

**Issue by k00r** [AlexeyAB/Yolo_mark#52]
Hello Alexey,i have two questions,i'll be glad if you answer them

1)Can we disable the command window when doing annotations?
2)Can we disable the rendered characters on the image when doing annotations?Because sometimes they can be a small object there and the characters cover it.

**Comment by AlexeyAB** [comment]
Hi,

1. Do you mean - to disable terminal? No. But why does it bother you?
2. May be I will add such feature.

**Comment by k00r** [comment]
1)It's just a preference =)
2)That would be nice
