### ISSUE TITLE
an idea to improve the validation of large datasets

### ISSUE THREAD

**Issue by k00r** [AlexeyAB/Yolo_mark#58]
Hello Alexey,i want to add a functionality to my version of this tool which will move the passed image (with the right arrow key or the space bar) and it's annotation file (.txt file) to another specified folder because when validating the annotations of large datasets it can take some days to complete and without this you will have to leave the pc running,and if you didn't take note of the last image or the index and something happens like a power failure or an error like BSOD you will lose the progress.Can you point me to the code line where the tool saves the annotation to the text file and moves on to the next image so i can insert few lines of code in there to create this functionality.

**Comment by AlexeyAB** [comment]
@k00r Hi,

What progress do you want to save? When you go to the new image by click (or arrow key), the txt-label file will be saved to the disk. So after BSOD, you just can open your dataset, and list images (hold SPACE-key) until the image will not have labels.

In this part of code the txt-label will be saved: https://github.com/AlexeyAB/Yolo_mark/blob/5082b30c51b13dbef4da1f8b407997a5320da267/main.cpp#L344-L374

**Comment by k00r** [comment]
no,for example you want to change some annotations on a previously annotated dataset or add a new object class,in these cases there is no way of knowing your progress because all of the image files will have labels.I want to move the checked image and it's text file to another folder after the yolo_mark tool's save operation.

**Comment by AlexeyAB** [comment]
May be you can try to sort txt-labels by date of creation.

Or as you want - you can try to save new labels to the new directory - just change this line: https://github.com/AlexeyAB/Yolo_mark/blob/5082b30c51b13dbef4da1f8b407997a5320da267/main.cpp#L351
To something like this:
`std::string const txt_filename_path = images_path + "/new_directory/" + txt_filename; `

**Comment by k00r** [comment]
i want to move the image also,i want something like this;
-right arrow key pressed
-annotations are saved to the text file
-move the text file and the image file to the new folder
-jump to the next image
