### ISSUE TITLE
Undo

### ISSUE THREAD

**Issue by ido-ran** [AlexeyAB/Yolo_mark#62]
Hi,
Is it possible to undo the last mark instead of clearing everything?

It happens a lot that a mark is drawn wrong and I want to remove it the last action, not everything.

**Comment by AlexeyAB** [comment]
Hi, at this moment there is no such feature.

**Comment by ido-ran** [comment]
I’ll be glad to take a try at it, do you have any pointers?

**Comment by AlexeyAB** [comment]
Now you can use `Z` button to undo - to remove the last bounded box.

**Comment by ido-ran** [comment]
Thank you
