### ISSUE TITLE
Remove a specific tag from many | Enhancement

### ISSUE THREAD

**Issue by dexception** [AlexeyAB/Yolo_mark#67]
I have lots of images of people in crowded places but with lot of false positives. Is it possible to remove specific rectangles by clicking the cross button on top right corner ? or right click then select remove ?
I would be able to retrain my model by remove them from the dataset.

Thanks !

**Comment by dexception** [comment]
@AlexeyAB 
If you can find time to implement this one feature. I would be able to increase accuracy by 10 folds.

**Comment by AlexeyAB** [comment]
@dexception 
* I added this feature. Select any bbox by moving cursor inside the bbox. Then press `r` button - to delete it.
* Also you can move any bbox by usinr Right mouse button.
