### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by PranjaLBiswas27** [AlexeyAB/Yolo_mark#81]
On running the command: ./linux_mark.sh, I get the following error,

Example how to start marking bouded boxes for training set Yolo v2
./linux_mark.sh: line 4: ./yolo_mark: No such file or directory
./linux_mark.sh: line 7: pause: command not found

I did cmake and make the file successfully before running the bash file. What is going wrong here. Please let me know. Thanks a lot in advance.

**Comment by AlexeyAB** [comment]
> I did cmake and make the file successfully before running the bash file. 

Can you show screenshot?

**Comment by PranjaLBiswas27** [comment]
![screenshot from 2018-08-27 00-59-50](https://user-images.githubusercontent.com/38991742/44634172-53262f00-a996-11e8-9eda-f448f80bd5f6.png)

Sorry, on reading carefully i see that make failed. What is the issue here in this case and how can I resolve it?

**Comment by PranjaLBiswas27** [comment]
I was able to solve this issue by building opencv from source instead of using pre-build binaries. Although I don't know how does that help.
