### ISSUE TITLE
Can't install this after git clonning 

### ISSUE THREAD

**Issue by vg123** [AlexeyAB/Yolo_mark#9]
I am following this [link](https://github.com/AlexeyAB/Yolo_mark) and want to use `Yolo_mark` to find these parameters `<x><y><width><height>`
`<x> = <absolute_x>/<width_of_image>`
`<y>=<absolute_y>/<height_of_image>`
`<width> = <width_of_object>/<width_of_image>`
`<height> = <height_of_object>/<height_of_image>`

so after `git clone` [link](https://github.com/AlexeyAB/Yolo_mark.git) I get into the folder of `yolo_mark`  and now followed the instructions that is 
`cmake .` 
```
CMake Error at CMakeLists.txt:3 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!

Please help me, to come to this problem , I want to use this `yolo_mark` finally to detect objects in the image
```

**Comment by AlexeyAB** [comment]
Do you have installed library OpenCV?

**Comment by vg123** [comment]
yes i do have with version 2

**Comment by vg123** [comment]
`yolo_mark.cmd ` is not running but I can use `yolo_mark `'s  interface for finding `<x><y><width><height>`. Will there be any problem in it ?

**Comment by AlexeyAB** [comment]
There is no problem.

yolo_mark.cmd - only for Windows OS.

----

https://github.com/AlexeyAB/Yolo_mark#yolo_mark

> To test, simply run
> * on Windows: x64/Release/yolo_mark.cmd
> * **on Linux ./linux_mark.sh**

**Comment by vg123** [comment]
Ok thanks a lot .
